// Interpretations for Astro-Numerology and Geo-Numerology

export const PLANET_INFLUENCES: Record<string, string> = {
  "soleil": "Le Soleil représente votre essence vitale, votre volonté et votre rayonnement conscient. C'est le centre de votre système personnel, la force qui vous pousse à briller, à prendre votre place de leader et à exprimer votre individualité sans compromis. Son influence vous donne le courage d'être vous-même et de diriger votre vie avec clarté. Votre défi est d'apprendre à rayonner de manière généreuse sans brûler les autres par un ego trop dominant.",
  "lune": "La Lune gouverne vos émotions, vos instincts primaires, votre intuition et votre monde intérieur privé. Elle représente votre besoin de sécurité, la manière dont vous réagissez instinctivement aux événements et votre part de mystère. Elle vous confère une grande sensibilité et une imagination fertile qui peut nourrir de grands projets. Votre force réside dans votre intelligence émotionnelle et votre capacité à créer un cocon protecteur pour vous et vos proches.",
  "jupiter": "Jupiter est la planète de l'expansion, de la chance, de la sagesse et de la vision globale. Elle agit comme un amplificateur de vos talents et de vos opportunités. Elle vous invite à voir grand, à explorer de nouveaux horizons (qu'ils soient physiques, intellectuels ou spirituels) et à partager vos connaissances avec enthousiasme. Son influence vous pousse à la bienveillance et à la recherche d'un sens supérieur à l'existence, vous aidant à attirer l'abondance par votre optimisme.",
  "uranus": "Uranus est l'éveilleur, la planète du changement soudain, de l'originalité et de l'innovation radicale. Elle représente votre besoin de liberté absolue et votre capacité à penser en dehors des sentiers battus. Son influence vous pousse à briser les codes obsolètes, à vous libérer des traditions qui vous emprisonnent et à affirmer votre génie unique. C'est l'énergie du futuriste et du réformateur qui n'a pas peur de provoquer le chaos pour reconstruire sur des bases plus vraies.",
  "mercure": "Mercure est le messager, maître absolu de la communication, de l'intellect et de l'agilité mentale. Il régit la manière dont vous percevez l'information, dont vous apprenez et dont vous transmettez vos idées. Il vous dote d'une vivacité d'esprit exceptionnelle, d'une curiosité insatiable et d'une capacité d'adaptation rapide à n'importe quel environnement. Votre arme la plus puissante est votre intelligence tactique et votre talent pour créer des ponts entre les idées et les gens.",
  "venus": "Vénus incarne l'amour, l'harmonie, les valeurs personnelles et le sens esthétique. Elle régit ce que vous aimez, la manière dont vous attirez ce que vous désirez et votre recherche d'équilibre dans les relations. Elle vous oriente vers la diplomatie, la création de beauté et la jouissance des plaisirs de la vie. Votre talent majeur est votre charme naturel et votre capacité à pacifier les tensions pour instaurer un climat de bien-être et de raffinement autour de vous.",
  "neptune": "Neptune est la planète du rêve, de la spiritualité transcendante et de la dissolution des frontières. Elle vous connecte aux plans subtils de l'existence et développe votre empathie universelle. Son influence affine votre intuition jusqu'à la clairvoyance et nourrit une inspiration artistique presque mystique. Elle vous demande de lâcher prise sur le contrôle matériel pour naviguer dans l'océan de l'inconscient, tout en veillant à ne pas vous perdre dans les illusions ou la fuite de la réalité.",
  "saturne": "Saturne est le grand architecte du zodiaque, maître du temps, de la structure et des leçons de vie nécessaires. Loin d'être purement restrictif, il représente votre capacité de concentration, votre discipline et votre intégrité. Il vous demande de la patience et de la persévérance pour bâtir des fondations solides et durables. Son influence vous enseigne que la véritable liberté s'acquiert par la maîtrise de soi et la prise de responsabilité totale sur votre destinée.",
  "mars": "Mars est l'énergie brute de l'action, du désir pur, du courage et de la conquête. Il représente votre capacité à vous affirmer, à défendre vos limites et à surmonter les obstacles de front. C'est votre guerrier intérieur, le carburant qui vous permet d'initier des projets audacieux et de transformer vos intentions en actes concrets. Bien canalisé, il vous donne une force de frappe et une endurance physique et mentale hors du commun pour triompher des défis."
};

export const ZODIAC_DETAILS: Record<string, { element: string, quality: string, description: string, moonDesc: string, ascendantDesc: string }> = {
  "bélier": {
    element: "Feu",
    quality: "Cardinal",
    description: "Premier signe du zodiaque, le Bélier incarne l'étincelle de vie initiale, l'élan pur et l'audace sans filtre. Vous possédez une force d'initiation brute qui vous pousse à agir avant même de réfléchir, guidé par un instinct infaillible. Votre mission solaire est d'ouvrir de nouvelles voies, de prendre la tête de projets novateurs et d'affirmer votre identité avec courage. Vous détestez la stagnation et la bureaucratie; vous avez besoin de défis constants pour vous sentir vivant. Apprenez à canaliser votre impatience pour que votre feu intérieur soit une source de chaleur constante plutôt qu'un incendie passager.",
    moonDesc: "Avec la Lune en Bélier, votre monde émotionnel est un champ de bataille ou un terrain d'aventure permanent. Vos réactions sont instantanées, franches et parfois explosives. Vous avez un besoin vital d'action pour vous sentir en sécurité émotionnelle; l'attente ou l'indécision vous angoissent physiquement. Vous êtes une personne d'une grande honnêteté sentimentale, incapable de cacher ce que vous ressentez. Votre courage émotionnel vous permet de surmonter les crises avec une rapidité déconcertante, car vous préférez affronter le problème de face plutôt que de ruminer dans l'ombre.",
    ascendantDesc: "L'Ascendant Bélier vous donne une aura de force, de franchise et de détermination immédiate. On vous perçoit comme quelqu'un de direct, d'énergique et souvent de sportif ou de très actif physiquement. Vous abordez la vie avec une certaine naïveté héroïque, prêt à relever tous les défis sans vous poser de questions. Votre première réaction face à n'importe quelle situation est l'action ou la confrontation constructive. Vous dégagez une impression de jeunesse et de vitalité qui inspire confiance à ceux qui cherchent un leader pour initier un mouvement."
  },
  "taureau": {
    element: "Terre",
    quality: "Fixe",
    description: "Le Taureau est le bâtisseur du zodiaque, celui qui donne forme, stabilité et valeur à la matière. Vous possédez un lien viscéral avec la terre, la nature et tout ce qui est tangible. Votre Soleil vous invite à construire quelque chose de durable, que ce soit un patrimoine, une famille ou une œuvre d'art. Vous avancez avec une patience légendaire et une ténacité que rien ne peut briser. Vous avez un goût prononcé pour le confort et les plaisirs sensoriels (gastronomie, art, toucher), car ils sont pour vous des ancres nécessaires. Votre défi est d'accepter le changement et de ne pas laisser votre besoin de sécurité se transformer en une obstination stérile.",
    moonDesc: "La Lune est en exaltation en Taureau, ce qui vous donne l'un des mondes émotionnels les plus stables et les plus riches du zodiaque. Vos émotions sont profondes, calmes et persistantes. Pour vous sentir bien, vous avez besoin de sécurité matérielle, de routines apaisantes et d'un environnement esthétique. Vous n'aimez pas les drames émotionnels inutiles et préférez exprimer votre affection par des gestes concrets : un bon repas, un cadeau de qualité ou une présence physique rassurante. Votre paix intérieure se trouve dans le contact avec la nature et la lenteur, loin du tumulte du monde moderne.",
    ascendantDesc: "L'Ascendant Taureau vous confère une présence physique solide, calme et souvent très séduisante. Vous dégagez une impression de fiabilité et de bon sens qui rassure instantanément votre entourage. Vous abordez la vie avec prudence, prenant le temps de observer avant de vous engager, mais une fois lancé, rien ne peut vous arrêter. On remarque chez vous un amour pour la qualité et le beau, que ce soit dans votre tenue ou votre manière de parler. Votre rythme est lent mais puissant, et vous possédez un talent naturel pour faire fructifier les ressources autour de vous."
  },
  "gémeaux": {
    element: "Air",
    quality: "Mutable",
    description: "Signe de la dualité et de l'échange, le Gémeaux est l'éternel étudiant du zodiaque. Votre esprit est une machine à traiter l'information, toujours en quête de nouvelles connaissances, de nouveaux liens et de nouvelles perspectives. Votre Soleil vous pousse à communiquer, à écrire, à parler et à diffuser des idées. Vous possédez une agilité mentale et une adaptabilité qui vous permettent de naviguer avec aisance dans des environnements complexes ou changeants. Votre curiosité insatiable fait de vous une personne polyvalente, capable de s'intéresser à mille sujets. Votre défi est de trouver un fil conducteur pour ne pas vous éparpiller et pour donner de la profondeur à vos multiples talents.",
    moonDesc: "Avec la Lune en Gémeaux, vos émotions passent par le filtre de l'intellect. Vous avez besoin de comprendre, d'analyser et surtout de verbaliser ce que vous ressentez pour vous sentir en sécurité. Votre monde intérieur est vif, curieux et parfois agité. Vous détestez l'ennui émotionnel et avez besoin de stimulation mentale constante, même dans vos relations intimes. Vous êtes capable de parler de vos sentiments avec beaucoup d'esprit et d'humour, ce qui peut parfois donner l'impression d'un certain détachement, alors qu'il s'agit simplement de votre manière de traiter la complexité de votre cœur.",
    ascendantDesc: "L'Ascendant Gémeaux vous donne une allure juvénile, mobile et extrêmement sociable. On vous perçoit comme quelqu'un d'intelligent, de curieux et de toujours prêt à engager la conversation. Vous avez un besoin constant de mouvement, que ce soit par le voyage, la lecture ou les rencontres. Votre approche de la vie est légère, ludique et pleine d'humour. Vous entrez en contact avec le monde extérieur par la parole et les idées, ce qui fait de vous un excellent communicateur ou médiateur. Votre curiosité naturelle vous pousse à explorer sans cesse de nouveaux horizons, faisant de vous une personne toujours 'à la page'."
  },
  "cancer": {
    element: "Eau",
    quality: "Cardinal",
    description: "Le Cancer est le gardien des émotions, des racines et de l'intimité. Signe d'eau régi par la Lune, vous possédez une sensibilité extrême et une intuition qui frise la clairvoyance. Votre Soleil vous demande de créer un sanctuaire, que ce soit votre foyer ou votre cercle proche, où vous pouvez nourrir et protéger ceux que vous aimez. Vous êtes le lien entre le passé et le présent, très attaché à la famille et aux souvenirs. Votre force réside dans votre capacité d'empathie et votre ténacité silencieuse pour défendre votre 'clan'. Votre défi est de sortir de votre carapace pour ne pas vous laisser submerger par vos propres vagues émotionnelles ou par celles des autres.",
    moonDesc: "La Lune est chez elle en Cancer, ce qui décuple votre réceptivité. Vous êtes une véritable éponge émotionnelle, ressentant les ambiances et les non-dits avant même qu'une parole soit prononcée. Votre besoin de sécurité émotionnelle est immense et passe par le sentiment d'appartenance et la protection de votre vie privée. Votre monde intérieur est vaste, peuplé de rêves et de souvenirs profonds. Vous avez un talent inné pour prendre soin des autres et pour créer une atmosphère chaleureuse. Votre humeur peut fluctuer comme les marées, mais votre cœur reste fidèle et protecteur envers ceux qui ont gagné votre confiance.",
    ascendantDesc: "L'Ascendant Cancer vous donne une apparence douce, réceptive et parfois un peu réservée au premier abord. Vous abordez le monde avec prudence, comme si vous aviez besoin de tester l'ambiance émotionnelle avant de vous dévoiler. On perçoit chez vous une grande bienveillance et un instinct protecteur qui se manifeste naturellement. Votre visage est souvent très expressif, reflétant vos émotions changeantes. Vous attirez les autres par votre capacité d'écoute et votre chaleur humaine, et on vient souvent vers vous pour chercher du réconfort ou des conseils intuitifs."
  },
  "lion": {
    element: "Feu",
    quality: "Fixe",
    description: "Le Lion est le monarque solaire du zodiaque, celui qui apporte la lumière, la chaleur et la créativité. Vous possédez un charisme naturel et un besoin vital d'exprimer votre unicité. Votre Soleil vous invite à briller, à créer et à inspirer les autres par votre générosité et votre noblesse de cœur. Vous avez un sens inné de la mise en scène et vous ne supportez pas la médiocrité ou l'ombre. Votre force réside dans votre loyauté sans faille et votre capacité à porter des projets ambitieux avec une confiance inébranlable. Votre défi est d'apprendre que la véritable autorité n'a pas besoin de reconnaissance constante et de cultiver une humilité qui servira votre grandeur naturelle.",
    moonDesc: "Avec la Lune en Lion, votre cœur a besoin de se sentir spécial, admiré et respecté pour être en paix. Vos émotions sont nobles, chaleureuses et parfois théâtrales. Vous avez un besoin immense de reconnaissance affective et vous donnez votre amour avec une générosité royale. Vous ne supportent pas d'être ignoré ou traité de manière banale. Votre monde intérieur est peuplé de rêves de grandeur et de beauté. Malgré votre fierté apparente, vous possédez une vulnérabilité touchante car vous avez besoin que l'on valide votre valeur. En sécurité, vous êtes la personne la plus loyale et la plus encourageante qui soit.",
    ascendantDesc: "L'Ascendant Lion vous confère une présence solaire, digne et immédiatement remarquable. Vous dégagez une aura de confiance, de chaleur et d'autorité naturelle. Votre démarche est souvent assurée, et vous accordez une grande importance à votre image et à votre allure. Vous abordez la vie avec enthousiasme et créativité, cherchant toujours à laisser votre empreinte sur ce que vous entreprenez. On vous perçoit comme quelqu'un de généreux, de protecteur et de charismatique, capable de motiver les foules par votre simple présence et votre optimisme communicatif."
  },
  "vierge": {
    element: "Terre",
    quality: "Mutable",
    description: "La Vierge est l'analyste et l'artisan du zodiaque, celle qui cherche la perfection par le service et le discernement. Votre esprit est d'une précision chirurgicale, capable de trier l'essentiel de l'accessoire. Votre Soleil vous guide vers l'excellence technique, l'humilité et le dévouement. Vous trouvez votre pleine réalisation en étant utile, en soignant, en organisant ou en optimisant les systèmes autour de vous. Vous avez un sens du détail et de la responsabilité qui fait de vous un pilier de fiabilité. Votre défi est de ne pas vous laisser paralyser par l'autocritique ou le souci du détail, et d'accepter que la perfection est un chemin, pas une fin en soi.",
    moonDesc: "Avec la Lune en Vierge, votre sécurité émotionnelle passe par l'ordre, la clarté et l'utilité pratique. Vous avez besoin d'analyser vos sentiments pour les comprendre et les 'ranger'. Votre monde intérieur est pudique et réservé, préférant les preuves d'amour concrètes et les services rendus aux grandes déclarations passionnées. Vous vous sentez bien quand votre quotidien est structuré et que vous pouvez aider les autres de manière efficace. Votre sensibilité se manifeste par un souci constant du bien-être de vos proches, veillant sur leur santé et leur confort avec une attention discrète mais infatigable.",
    ascendantDesc: "L'Ascendant Vierge vous donne une approche méthodique, discrète et très observatrice de la vie. On vous perçoit comme quelqu'un de soigné, de réservé et d'une grande intelligence pratique. Vous abordez chaque nouvelle situation avec un regard critique et analytique, cherchant d'abord à comprendre comment les choses fonctionnent. Votre communication est précise et réfléchie. Vous dégagez une impression de compétence et de modestie qui inspire un profond respect. Vous avez un talent naturel pour l'organisation et vous êtes souvent la personne vers qui l'on se tourne pour résoudre des problèmes complexes avec calme et efficacité."
  },
  "balance": {
    element: "Air",
    quality: "Cardinal",
    description: "La Balance est le diplomate et l'esthète du zodiaque, en quête perpétuelle d'harmonie et de justice. Régi par Vénus, votre signe est celui de la relation et de l'équilibre entre les contraires. Votre Soleil vous demande de pacifier les tensions, de créer de la beauté et de collaborer avec les autres. Vous possédez un sens inné de la justice et une capacité à voir tous les aspects d'une situation, ce qui fait de vous un excellent médiateur. Vous vous réalisez pleinement à travers l'autre, dans le couple ou les partenariats. Votre défi est d'apprendre à prendre des décisions fermes et à affirmer votre propre vérité, même si cela risque de briser l'harmonie apparente.",
    moonDesc: "Avec la Lune en Balance, votre équilibre émotionnel est intrinsèquement lié à l'harmonie de vos relations. Le conflit vous est physiquement et psychologiquement insupportable. Pour vous sentir en sécurité, vous avez besoin de calme, de beauté et surtout de partage. Vous avez horreur de la solitude prolongée et vous vous sentez 'entier' seulement au contact des autres. Vos émotions sont nuancées, raffinées et portées vers la conciliation. Vous possédez un charme naturel et une courtoisie émotionnelle qui vous permettent de désamorcer les tensions avec élégance, cherchant toujours le point d'équilibre entre vos besoins et ceux d'autrui.",
    ascendantDesc: "L'Ascendant Balance vous confère un charme évident, une élégance naturelle et une grande sociabilité. Vous abordez le monde avec le désir sincère de plaire et de créer des connexions harmonieuses. On vous perçoit comme quelqu'un de gracieux, de poli et de très attentif aux autres. Vous avez un sens esthétique très développé qui se reflète dans votre apparence et votre environnement. Votre approche de la vie est diplomate et mesurée, cherchant toujours le compromis et la collaboration. Vous dégagez une aura de paix et de raffinement qui attire naturellement les gens vers vous, faisant de vous un pivot social indispensable."
  },
  "scorpion": {
    element: "Eau",
    quality: "Fixe",
    description: "Le Scorpion est l'alchimiste du zodiaque, celui qui plonge dans les profondeurs pour transformer l'ombre en lumière. Vous possédez une intensité émotionnelle et une puissance psychologique hors du commun. Votre Soleil vous invite à embrasser les cycles de mort et de renaissance, à explorer les mystères de l'existence et à vivre avec une passion totale. Rien de ce qui est superficiel ne vous intéresse; vous cherchez la vérité nue, coûte que coûte. Votre force réside dans votre résilience, votre magnétisme et votre loyauté absolue envers ceux que vous avez choisi d'aimer. Votre défi est d'apprendre à lâcher prise sur le contrôle et à utiliser votre puissance pour guérir plutôt que pour détruire.",
    moonDesc: "Avec la Lune en Scorpion (position de chute, mais d'une force immense), vos émotions sont océaniques, secrètes et d'une intensité absolue. Vous ne ressentez rien à moitié. Pour vous sentir en sécurité, vous avez besoin de vérité, de profondeur et d'une intimité fusionnelle. Vous possédez un radar infaillible pour détecter le mensonge et la manipulation. Votre monde intérieur est un sanctuaire protégé où vous transformez vos crises en force de vie. Vous êtes capable d'un dévouement total et d'une protection féroce envers vos proches. Votre sensibilité est votre plus grand pouvoir, vous permettant de comprendre les motivations les plus cachées de l'âme humaine.",
    ascendantDesc: "L'Ascendant Scorpion vous donne une présence magnétique, mystérieuse et d'une intensité qui ne laisse personne indifférent. On vous perçoit comme quelqu'un de profond, de secret et doté d'une grande force intérieure. Vous abordez la vie avec une vigilance instinctive, scannant votre environnement avec perspicacité avant de vous engager. Votre regard est souvent perçant, semblant voir au-delà des apparences. Vous dégagez une impression de puissance retenue et de sang-froid qui impose le respect. On sent chez vous une capacité à gérer les crises et les situations complexes avec une détermination inébranlable, faisant de vous un allié précieux dans les moments difficiles."
  },
  "sagittaire": {
    element: "Feu",
    quality: "Mutable",
    description: "Le Sagittaire est l'explorateur et le philosophe du zodiaque, assoiffé de liberté, de sens et de grands horizons. Régi par Jupiter, votre signe est celui de l'expansion et de la quête spirituelle. Votre Soleil vous appelle à l'aventure, qu'elle soit géographique, intellectuelle ou intérieure. Vous possédez un optimisme naturel et une foi en la vie qui vous permettent de surmonter tous les obstacles. Votre mission est de chercher la vérité, de comprendre les lois de l'univers et de transmettre votre enthousiasme aux autres. Vous avez besoin d'espace et d'indépendance pour vous épanouir. Votre défi est d'apprendre la discipline et de ne pas fuir les responsabilités quotidiennes au nom d'un idéal lointain.",
    moonDesc: "Avec la Lune en Sagittaire, votre sécurité émotionnelle est directement liée à votre sentiment de liberté et à votre capacité d'expansion. Vous avez besoin d'espace physique et mental pour vous sentir bien. L'optimisme est votre mécanisme de défense naturel : face à la douleur, vous cherchez toujours le sens ou la leçon positive. Votre monde intérieur est vaste, joyeux et porté vers l'avenir. Vous avez besoin de croire en quelque chose de plus grand que vous pour être en paix. Vos émotions sont franches, directes et enthousiastes. Vous trouvez votre équilibre dans le voyage, l'étude philosophique et le partage d'idées inspirantes avec vos proches.",
    ascendantDesc: "L'Ascendant Sagittaire vous dote d'une énergie enthousiaste, bienveillante et résolument tournée vers l'aventure. On vous perçoit comme quelqu'un d'ouvert, de jovial et d'une grande franchise. Vous abordez la vie comme une quête permanente, avec une soif de découverte qui se lit sur votre visage. Votre démarche est souvent rapide, comme si vous étiez toujours en route vers un nouvel horizon. Vous dégagez une aura de sagesse et d'optimisme qui attire ceux qui cherchent une direction ou un sens à leur vie. Votre approche est amicale et sans jugement, faisant de vous une personne très appréciée pour sa tolérance et sa vision inspirante du futur."
  },
  "capricorne": {
    element: "Terre",
    quality: "Cardinal",
    description: "Le Capricorne est le stratège et le bâtisseur de sommets du zodiaque. Régi par Saturne, votre signe incarne la responsabilité, l'intégrité et la persévérance. Votre Soleil vous demande de structurer votre vie avec rigueur, de prendre des responsabilités et de réaliser des ambitions concrètes qui dureront dans le temps. Vous possédez une maturité précoce et un sens du devoir qui vous poussent à viser l'excellence. Votre force réside dans votre patience légendaire et votre capacité à transformer les épreuves en pierres d'angle pour votre réussite. Votre défi est d'apprendre à ouvrir votre cœur et à ne pas laisser votre ambition ou votre besoin de contrôle vous couper de votre sensibilité et de votre joie intérieure.",
    moonDesc: "Avec la Lune en Capricorne (position d'exil, mais d'une grande dignité), vous gérez vos émotions avec une pudeur et une réserve extrêmes. Pour vous sentir en sécurité, vous avez besoin de structure, d'utilité et de respect. Vous exprimez votre affection par des actes concrets de responsabilité et de protection matérielle plutôt que par des mots doux. Votre monde intérieur est sérieux, ambitieux et tourné vers la maîtrise de soi. Vous possédez une résilience émotionnelle hors du commun, capable d'assumer des charges lourdes sans vous plaindre. Votre paix intérieure se trouve dans la réussite de vos objectifs et dans le sentiment d'avoir bâti quelque chose de solide pour vous et les vôtres.",
    ascendantDesc: "L'Ascendant Capricorne vous confère une allure sérieuse, mature et d'une grande dignité naturelle. On vous perçoit comme quelqu'un de compétent, de fiable et d'une autorité tranquille. Vous abordez la vie avec prudence et pragmatisme, planifiant vos actions sur le long terme. Votre présentation est souvent sobre et soignée, reflétant votre besoin de respectabilité. Vous dégagez une impression de solidité qui inspire confiance aux décideurs et aux partenaires. Votre approche est méthodique et vous accordez une grande valeur au temps et à l'effort. On sent chez vous une ambition calme mais inébranlable, capable de franchir tous les obstacles par la simple force de la volonté."
  },
  "verseau": {
    element: "Air",
    quality: "Fixe",
    description: "Le Verseau est le visionnaire et le réformateur du zodiaque, celui qui pense le futur et le collectif. Régi par Uranus, votre signe incarne la liberté, l'originalité et la fraternité universelle. Votre Soleil vous pousse à vous libérer des conditionnements sociaux, à innover et à défendre des valeurs humanistes. Vous possédez un esprit indépendant et une capacité à voir les choses sous un angle totalement nouveau. Vous vous réalisez pleinement au sein de groupes ou de causes qui visent à améliorer la société. Votre force réside dans votre idéalisme et votre détachement intellectuel. Votre défi est d'apprendre à connecter avec vos émotions personnelles et à ne pas rester trop 'dans votre tête' ou dans vos concepts abstraits.",
    moonDesc: "Avec la Lune en Verseau, votre sécurité émotionnelle passe par l'indépendance et le sentiment d'être unique. Vous avez besoin de liberté totale dans vos relations et vous avez horreur des drames passionnels ou de la possessivité. Votre monde intérieur est original, amical et tourné vers le collectif. Vous rationalisez souvent vos émotions pour mieux les comprendre, ce qui vous donne un air détaché mais cache une grande loyauté envers vos idéaux et vos amis. Vous vous sentez bien quand vous pouvez contribuer à un projet de groupe ou quand vous êtes entouré de personnes qui respectent votre besoin d'espace. Votre sensibilité est universelle, portée par une compassion pour l'humanité entière.",
    ascendantDesc: "L'Ascendant Verseau vous donne une apparence originale, amicale et résolument indépendante. On vous perçoit comme quelqu'un d'unique, d'un peu excentrique ou très moderne, avec un esprit libre d'anticonformisme. Vous abordez la vie avec curiosité et une ouverture d'esprit totale. Votre contact est facile mais garde toujours une certaine distance intellectuelle. Vous dégagez une aura de fraternité et de progrès qui attire ceux qui cherchent des solutions nouvelles ou une vision différente du monde. On sent chez vous un refus des conventions inutiles et une volonté de vivre selon vos propres règles, faisant de vous une source d'inspiration pour la liberté individuelle."
  },
  "poissons": {
    element: "Eau",
    quality: "Mutable",
    description: "Dernier signe du zodiaque, le Poissons est le mystique et l'empathique universel, celui qui clôt le cycle pour retourner à l'unité. Régi par Neptune, votre signe incarne la compassion, l'intuition et le lâcher-prise. Votre Soleil vous invite à explorer les plans subtils, à exprimer votre immense créativité artistique et à servir une cause plus grande que votre ego. Vous possédez une sensibilité qui frise la médiumnité et une capacité à ressentir la souffrance du monde. Votre force réside dans votre adaptabilité émotionnelle et votre foi en l'invisible. Votre défi est de mettre des limites saines pour ne pas vous laisser envahir par les émotions des autres et de trouver un ancrage dans la réalité matérielle.",
    moonDesc: "Avec la Lune en Poissons (position de grande dignité), votre sensibilité est sans limite et votre intuition est votre guide absolu. Vous êtes une véritable éponge psychique, absorbant les ambiances et les émotions environnantes de manière inconsciente. Votre sécurité émotionnelle passe par le retrait, le rêve, la musique ou la spiritualité. Votre monde intérieur est vaste, poétique et peuplé d'images riches. Vous avez un besoin immense de compassion et de douceur. Face aux difficultés, vous avez tendance à chercher refuge dans votre imaginaire ou dans la fusion avec l'autre. Votre force est votre capacité de pardon et votre amour inconditionnel qui peut guérir les cœurs les plus endurcis.",
    ascendantDesc: "L'Ascendant Poissons vous confère une présence insaisissable, douce et d'une grande poésie. On vous perçoit comme quelqu'un de rêveur, d'empathique et parfois de mystérieux. Vous abordez le monde avec intuition et fluidité, comme si vous glissiez entre les événements. Votre regard est souvent lointain ou empreint d'une grande nostalgie, reflétant votre connexion aux mondes subtils. On sent chez vous une vulnérabilité apparente qui cache en réalité une immense force d'adaptation. Vous attirez les autres par votre douceur et votre absence de jugement, créant naturellement un climat de confiance où chacun se sent compris sans avoir besoin de parler."
  }
};

export const HOUSE_MEANINGS: Record<number, { title: string, keywords: string, description: string, sunContext: string }> = {
  1: { 
    title: "Maison 1", 
    keywords: "Identité, Apparence, Élan Vital", 
    description: "La Maison 1, ou l'Ascendant, est le domaine de l'affirmation de soi, de l'image que vous projetez spontanément au monde et de votre constitution physique. C'est la 'porte d'entrée' de votre thème astral, indiquant comment vous initiez les choses et comment vous réagissez instinctivement aux nouvelles expériences.",
    sunContext: "Avec le Soleil en Maison 1, votre identité est votre priorité absolue. Vous êtes ici pour vous découvrir vous-même, pour briller par votre propre force et pour marquer le monde de votre empreinte personnelle. Votre réalisation passe par l'autonomie, le leadership et le courage d'être pleinement vous-même, sans compromis."
  },
  2: { 
    title: "Maison 2", 
    keywords: "Ressources, Valeurs, Sécurité Matérielle", 
    description: "Le domaine de vos acquis, de votre argent, de vos possessions, mais aussi de vos talents innés et de votre estime de soi. Elle décrit votre rapport à la matière et ce qui vous donne un sentiment de sécurité et de stabilité durable dans ce monde.",
    sunContext: "Le Soleil en Maison 2 met l'accent sur la construction d'une base solide. Votre réalisation passe par la valorisation de vos talents personnels et la création d'une sécurité matérielle qui reflète vos valeurs profondes. Vous brillez quand vous produisez quelque chose de concret, de beau et de durable."
  },
  3: { 
    title: "Maison 3", 
    keywords: "Communication, Apprentissage, Échanges", 
    description: "Le domaine de l'intellect proche, des échanges verbaux et écrits, des études courtes, de l'entourage immédiat (frères, sœurs, voisins) et des déplacements fréquents. Elle décrit votre manière de traiter l'information et de connecter les idées entre elles.",
    sunContext: "Le Soleil en Maison 3 illumine votre besoin de communiquer et d'apprendre. Vous vous réalisez à travers la parole, l'écriture ou la transmission de connaissances. Votre rayonnement dépend de votre capacité à rester curieux, à échanger avec fluidité et à créer des ponts intellectuels entre les gens."
  },
  4: { 
    title: "Maison 4", 
    keywords: "Racines, Foyer, Intimité Profonde", 
    description: "Le domaine de la famille, des origines, de la maison, mais aussi de votre fin de vie et de votre jardin secret. C'est la base de votre pyramide personnelle, le lieu où vous vous ressourcez et où vous cultivez votre sécurité émotionnelle la plus profonde.",
    sunContext: "Le Soleil en Maison 4 indique que votre force intérieure provient de vos racines. Votre réalisation passe par la construction d'un foyer stable, le soin apporté à votre clan et l'exploration de votre héritage familial. Vous brillez dans l'intimité et à travers la solidité de vos fondations émotionnelles."
  },
  5: { 
    title: "Maison 5", 
    keywords: "Créativité, Amour, Expression de Soi", 
    description: "Le domaine de la joie, des plaisirs, des amours, des enfants, des loisirs et de toute forme de création personnelle. C'est là que vous exprimez votre étincelle divine et que vous célébrez la vie avec enthousiasme et panache.",
    sunContext: "Le Soleil en Maison 5 vous pousse à briller par votre créativité et votre rayonnement personnel. Vous vous réalisez dans l'amour, le jeu et l'expression artistique. Votre mission est d'apporter de la joie et de la lumière autour de vous en osant être spectaculaire et passionné."
  },
  6: { 
    title: "Maison 6", 
    keywords: "Quotidien, Santé, Service Utile", 
    description: "Le domaine du travail quotidien, des tâches répétitives, de l'hygiène de vie, de la santé et du service aux autres. Elle décrit votre sens de l'organisation, votre habileté technique et votre besoin d'être efficace et utile concrètement.",
    sunContext: "Le Soleil en Maison 6 trouve son sens dans le service et le perfectionnement de soi. Votre réalisation passe par la maîtrise d'un savoir-faire, l'organisation rigoureuse de votre quotidien et le soin apporté à votre corps. Vous brillez par votre utilité et votre sens du devoir accompli."
  },
  7: { 
    title: "Maison 7", 
    keywords: "Relationnel, Couple, Partenariats", 
    description: "Le domaine de l'autre, du mariage, des contrats et de toutes les associations d'égal à égal. Elle décrit votre manière de collaborer, de négocier et de vous voir à travers le miroir de l'autre pour trouver l'équilibre et l'harmonie.",
    sunContext: "Le Soleil en Maison 7 indique que vous vous réalisez pleinement à travers vos relations. Votre rayonnement dépend de votre capacité à créer des unions harmonieuses et à collaborer avec équité. L'autre est le catalyseur de votre identité et de votre succès personnel."
  },
  8: { 
    title: "Maison 8", 
    keywords: "Transformation, Mystère, Renaissances", 
    description: "Le domaine des crises transformatrices, de la sexualité, de l'argent partagé (héritages, impôts), de l'occulte et de la psychologie profonde. C'est le lieu des métamorphoses où l'on meurt à une forme pour renaître à une autre, plus puissante.",
    sunContext: "Le Soleil en Maison 8 vous invite à explorer les profondeurs de l'âme et les mystères de la vie. Votre réalisation passe par des transformations intenses et la capacité à gérer des crises avec courage. Vous brillez par votre résilience et votre puissance de régénération intérieure."
  },
  9: { 
    title: "Maison 9", 
    keywords: "Expansion, Sagesse, Idéaux", 
    description: "Le domaine de la quête de sens, des voyages lointains (physiques ou spirituels), des études supérieures, de la loi et de la philosophie. Elle décrit votre besoin d'élargir vos horizons et de comprendre les lois universelles qui régissent le monde.",
    sunContext: "Le Soleil en Maison 9 vous pousse vers la quête de la vérité et de la sagesse. Vous vous réalisez dans l'exploration, l'enseignement ou la spiritualité. Votre rayonnement dépend de votre capacité à avoir une vision globale, optimiste et inspirante de l'existence."
  },
  10: { 
    title: "Maison 10", 
    keywords: "Vocation, Réussite Sociale, Destinée", 
    description: "Le domaine de la carrière, de la réputation publique, de l'ambition et de la mission de vie visible. Elle représente le sommet de votre thème astral, votre contribution à la société et la reconnaissance que vous recevez pour vos accomplissements.",
    sunContext: "Le Soleil en Maison 10 place votre réalisation au cœur de la sphère publique. Vous êtes ici pour réussir, pour prendre des responsabilités et pour construire une trajectoire visible et respectée. Vous brillez par votre ambition, votre intégrité et votre autorité naturelle."
  },
  11: { 
    title: "Maison 11", 
    keywords: "Projets Collectifs, Amis, Futurisme", 
    description: "Le domaine des espoirs, des projets à long terme, des groupes, des réseaux sociaux et des amitiés électives. Elle décrit votre vision pour l'avenir et votre capacité à collaborer au sein d'une communauté pour une cause commune.",
    sunContext: "Le Soleil en Maison 11 indique que votre épanouissement passe par le collectif. Vous vous réalisez en portant des projets novateurs et en fédérant les autres autour d'idéaux fraternels. Vous brillez par votre originalité et votre capacité à anticiper le futur."
  },
  12: { 
    title: "Maison 12", 
    keywords: "Inconscient, Spiritualité, Guérison de l'Âme", 
    description: "Le domaine du retrait, des épreuves secrètes, de la méditation, de l'inspiration mystique et du service désintéressé. C'est le lieu de la dissolution de l'ego où l'on se connecte à l'invisible et où l'on guérit les mémoires profondes.",
    sunContext: "Le Soleil en Maison 12 vous invite à une réalisation intérieure et spirituelle. Votre rayonnement est souvent discret mais puissant, passant par la compassion, le sacrifice noble ou la création artistique inspirée. Vous brillez dans le silence et le service à l'universel."
  }
};


export const PLACE_VIBRATIONS: Record<number, string> = {
  1: "Ce lieu vibre d'une énergie de commencement, d'individualité et d'ambition. C'est un endroit idéal pour entreprendre, se lancer en solo ou prendre un nouveau départ. L'atmosphère y est dynamique, parfois rapide, favorisant l'autonomie.",
  2: "Ce lieu porte une vibration de collaboration, de calme et de diplomatie. C'est un endroit propice aux couples, aux partenariats et à l'écoute. L'énergie y est douce, favorisant la patience et les détails plutôt que la vitesse.",
  3: "Ce lieu rayonne de créativité, de communication et de vie sociale. C'est un endroit stimulant, joyeux, où les échanges sont favorisés. Idéal pour les artistes, les commerçants et ceux qui cherchent à s'exprimer.",
  4: "Ce lieu incarne la structure, la sécurité et le travail. C'est un endroit solide, organisé, parfois un peu rigide, mais extrêmement rassurant. Idéal pour construire, s'enraciner et travailler avec discipline.",
  5: "Ce lieu vibre de changement, de liberté et de mouvement. C'est un endroit où tout bouge vite, propice aux voyages, à l'aventure et à l'adaptabilité. Il peut être instable mais jamais ennuyeux.",
  6: "Ce lieu dégage une énergie de responsabilité, d'harmonie familiale et de soin. C'est le nid idéal, propice au foyer, à la communauté et au bien-être. L'esthétique et le confort y sont importants.",
  7: "Ce lieu invite à l'introspection, au calme et à l'étude. C'est un endroit spirituel ou intellectuel, parfois un peu isolé, qui favorise la réflexion profonde, la recherche et le repos de l'esprit.",
  8: "Ce lieu pulse d'une énergie de pouvoir, d'argent et de réussite matérielle. C'est un centre d'affaires, une ville ambitieuse où l'efficacité prime. Idéal pour les carrières ambitieuses et les projets financiers.",
  9: "Ce lieu porte une vibration universelle, humaniste et d'aboutissement. C'est un endroit ouvert sur le monde, favorisant la tolérance, les arts et l'altruisme. On y vient pour clore un chapitre ou s'ouvrir à l'universel."
};

export const RESONANCE_DETAILS: Record<string, string> = {
  "harmonie": "Cette vibration géographique est en phase naturelle avec votre Chemin de Vie. Le lieu agit comme un amplificateur de vos talents innés. Vous vous y sentirez 'chez vous' rapidement, et les opportunités sembleront venir avec plus de fluidité.",
  "dynamique": "Cette vibration géographique crée une friction stimulante avec votre Chemin de Vie. Ce n'est pas un lieu de repos, mais un lieu de croissance. Il vous mettra au défi de développer des qualités que vous ne possédez pas naturellement, accélérant ainsi votre évolution."
};